### ISSUE TITLE
smart ai question

### ISSUE THREAD

**Issue by cruzk20** [Katacka/Dominion#18]
this is almost purely for my own intrigue, what statistical models are you using to implement your smart AI? also, you mentioned that it searches for the "optimal" card, does it do that by comparing the outcomes of using each card?

this was a great presentation!!!

**Comment by Katacka** [comment]
The AI will pay attention to the treasures it has bought and the distribution of these treasures in an attempt to predict the likely value of its next hand. As for the optimal card, this is primarily based on the ideals of the BigMoney strategy (Gold/Provinces) however it defaults to high-cost action generating cards when the criteria for Gold/Provinces have not been met
